### ISSUE TITLE
Codebook struggles with comma in character vector

### ISSUE THREAD

**Issue by daaronr** [rubenarslan/codebook#42]
```
---
title: "Codebook: Donations to JustGiving Fundraiser pages "
author: "David Reinstein"
output:
  html_document:
  toc: true
code_folding: 'hide'
self_contained: 
pdf_document:
  toc: yes
toc_depth: 4
latex_engine: xelatex
---
```

```{r setup}

library(tidyverse)
library(codebook)


```
  
```{r simple-tibble}

df <- tibble(x = 1:2, y = c("hello, i", "john"))

```

## Add meta-data

```{r meta-data}

metadata(df)$name <- "donation data"

```

## Codebook

```{r codebook-generation, message=FALSE, warning=FALSE}



codebook(df, survey_repetition = "single", metadata_table = FALSE)

```

Knitting the above code (an Rmd file) in R-studio throws error:

```
Quitting from lines 25-76 (codebook_reprex.Rmd) 
Quitting from lines 41-46 (codebook_reprex.Rmd) 
Error in value[[3L]](cond) : 
 Could not summarise item y. Error in as.environment(where): using 'as.environment(NULL)' is defunct
Calls: <Anonymous> ... eval -> value -> value.Future -> resignalConditions
Execution halted
```

However, removing the comma in the first element of the y character vector in the tibble ...
```
df <- tibble(x = 1:2, y = c("hello i", "john"))
``` 

Does not throw this error.
